//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShinyMAUIApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShinyMAUIApp.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aBOUT.
        /// </summary>
        internal static string Settings_AboutTitle {
            get {
                return ResourceManager.GetString("Settings_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ssssss .
        /// </summary>
        internal static string Settings_AppleHealthNotConnectedTitle {
            get {
                return ResourceManager.GetString("Settings_AppleHealthNotConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdqwddf .
        /// </summary>
        internal static string Settings_AppleHealthTitle {
            get {
                return ResourceManager.GetString("Settings_AppleHealthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dasddd.
        /// </summary>
        internal static string Settings_CallTitle {
            get {
                return ResourceManager.GetString("Settings_CallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dasdasasd gyuyiuytutyuytnm .
        /// </summary>
        internal static string Settings_ClinicalServiceTitle {
            get {
                return ResourceManager.GetString("Settings_ClinicalServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdsad .
        /// </summary>
        internal static string Settings_ConnectedServicesTitle {
            get {
                return ResourceManager.GetString("Settings_ConnectedServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Preferences.
        /// </summary>
        internal static string Settings_DataPreferencesTitle {
            get {
                return ResourceManager.GetString("Settings_DataPreferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sources.
        /// </summary>
        internal static string Settings_DataSourcesTitle {
            get {
                return ResourceManager.GetString("Settings_DataSourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sadSDSA.
        /// </summary>
        internal static string Settings_FaqTitle {
            get {
                return ResourceManager.GetString("Settings_FaqTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddddd dwqwfsdfs.
        /// </summary>
        internal static string Settings_FitbitTitle {
            get {
                return ResourceManager.GetString("Settings_FitbitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsd dsfdasf.
        /// </summary>
        internal static string Settings_GarminTitle {
            get {
                return ResourceManager.GetString("Settings_GarminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADASDAD.
        /// </summary>
        internal static string Settings_GeneralTitle {
            get {
                return ResourceManager.GetString("Settings_GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdfggsfdgsfdg.
        /// </summary>
        internal static string Settings_NotConnectedTitle {
            get {
                return ResourceManager.GetString("Settings_NotConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD.
        /// </summary>
        internal static string Settings_PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("Settings_PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASDASDASDA.
        /// </summary>
        internal static string Settings_PushNotificationsTitle {
            get {
                return ResourceManager.GetString("Settings_PushNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        internal static string Settings_SignalTitle {
            get {
                return ResourceManager.GetString("Settings_SignalTitle", resourceCulture);
            }
        }
    }
}
